language: php

language: php
php:
  - '7.0'

before_script:
  - composer require satooshi/php-coveralls
  - composer install --dev

script:
- ./vendor/bin/phpunit --coverage-clover ./tests/logs/clover.xml

after_script:
- php vendor/bin/coveralls -v

after_script:
  - php vendor/bin/coveralls -v