language: php

language: php
php:
  - '7.0'

before_script:
  - composer require satooshi/php-coveralls
  - composer install --dev

script:
  - mkdir -p build/logs
  - phpunit --coverage-clover build/logs/clover.xml

after_script:
  - php vendor/bin/coveralls -v